[package]
name = "cch23-vanhouc"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
axum-macros = "0.4.1"
base64 = "0.21.7"
serde = "1.0"
serde_json = "1.0"
shuttle-axum = "0.39.0"
shuttle-runtime = "0.39.0"
tokio = "1.36"
tracing = "0.1.40"
